//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"github.com/awslabs/operatorpkg/status"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttachVolumeDetails) DeepCopyInto(out *AttachVolumeDetails) {
	*out = *in
	in.VolumeFilter.DeepCopyInto(&out.VolumeFilter)
	in.CreateVolumeDetails.DeepCopyInto(&out.CreateVolumeDetails)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttachVolumeDetails.
func (in *AttachVolumeDetails) DeepCopy() *AttachVolumeDetails {
	if in == nil {
		return nil
	}
	out := new(AttachVolumeDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootVolumeConfig) DeepCopyInto(out *BootVolumeConfig) {
	*out = *in
	if in.ImageConfig != nil {
		in, out := &in.ImageConfig, &out.ImageConfig
		*out = new(ImageConfig)
		(*in).DeepCopyInto(*out)
	}
	in.VolumeAttribute.DeepCopyInto(&out.VolumeAttribute)
	if in.PvEncryptionInTransit != nil {
		in, out := &in.PvEncryptionInTransit, &out.PvEncryptionInTransit
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootVolumeConfig.
func (in *BootVolumeConfig) DeepCopy() *BootVolumeConfig {
	if in == nil {
		return nil
	}
	out := new(BootVolumeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityReservation) DeepCopyInto(out *CapacityReservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityReservation.
func (in *CapacityReservation) DeepCopy() *CapacityReservation {
	if in == nil {
		return nil
	}
	out := new(CapacityReservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityReservationConfig) DeepCopyInto(out *CapacityReservationConfig) {
	*out = *in
	if in.CapacityReservationId != nil {
		in, out := &in.CapacityReservationId, &out.CapacityReservationId
		*out = new(string)
		**out = **in
	}
	if in.CapacityReservationFilter != nil {
		in, out := &in.CapacityReservationFilter, &out.CapacityReservationFilter
		*out = new(OciResourceSelectorTerm)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityReservationConfig.
func (in *CapacityReservationConfig) DeepCopy() *CapacityReservationConfig {
	if in == nil {
		return nil
	}
	out := new(CapacityReservationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPlacementGroup) DeepCopyInto(out *ClusterPlacementGroup) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPlacementGroup.
func (in *ClusterPlacementGroup) DeepCopy() *ClusterPlacementGroup {
	if in == nil {
		return nil
	}
	out := new(ClusterPlacementGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPlacementGroupConfig) DeepCopyInto(out *ClusterPlacementGroupConfig) {
	*out = *in
	if in.ClusterPlacementGroupId != nil {
		in, out := &in.ClusterPlacementGroupId, &out.ClusterPlacementGroupId
		*out = new(string)
		**out = **in
	}
	if in.ClusterPlacementGroupFilter != nil {
		in, out := &in.ClusterPlacementGroupFilter, &out.ClusterPlacementGroupFilter
		*out = new(OciResourceSelectorTerm)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPlacementGroupConfig.
func (in *ClusterPlacementGroupConfig) DeepCopy() *ClusterPlacementGroupConfig {
	if in == nil {
		return nil
	}
	out := new(ClusterPlacementGroupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeCluster) DeepCopyInto(out *ComputeCluster) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeCluster.
func (in *ComputeCluster) DeepCopy() *ComputeCluster {
	if in == nil {
		return nil
	}
	out := new(ComputeCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeClusterConfig) DeepCopyInto(out *ComputeClusterConfig) {
	*out = *in
	if in.ComputeClusterId != nil {
		in, out := &in.ComputeClusterId, &out.ComputeClusterId
		*out = new(string)
		**out = **in
	}
	if in.ComputeClusterFilter != nil {
		in, out := &in.ComputeClusterFilter, &out.ComputeClusterFilter
		*out = new(OciResourceSelectorTerm)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeClusterConfig.
func (in *ComputeClusterConfig) DeepCopy() *ComputeClusterConfig {
	if in == nil {
		return nil
	}
	out := new(ComputeClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Image) DeepCopyInto(out *Image) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Image.
func (in *Image) DeepCopy() *Image {
	if in == nil {
		return nil
	}
	out := new(Image)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageConfig) DeepCopyInto(out *ImageConfig) {
	*out = *in
	if in.ImageFilter != nil {
		in, out := &in.ImageFilter, &out.ImageFilter
		*out = new(ImageSelectorTerm)
		(*in).DeepCopyInto(*out)
	}
	if in.ImageId != nil {
		in, out := &in.ImageId, &out.ImageId
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageConfig.
func (in *ImageConfig) DeepCopy() *ImageConfig {
	if in == nil {
		return nil
	}
	out := new(ImageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageSelectorTerm) DeepCopyInto(out *ImageSelectorTerm) {
	*out = *in
	if in.CompartmentId != nil {
		in, out := &in.CompartmentId, &out.CompartmentId
		*out = new(string)
		**out = **in
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]map[string]string, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageSelectorTerm.
func (in *ImageSelectorTerm) DeepCopy() *ImageSelectorTerm {
	if in == nil {
		return nil
	}
	out := new(ImageSelectorTerm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ipv6AddressIpv6SubnetCidrPairDetails) DeepCopyInto(out *Ipv6AddressIpv6SubnetCidrPairDetails) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ipv6AddressIpv6SubnetCidrPairDetails.
func (in *Ipv6AddressIpv6SubnetCidrPairDetails) DeepCopy() *Ipv6AddressIpv6SubnetCidrPairDetails {
	if in == nil {
		return nil
	}
	out := new(Ipv6AddressIpv6SubnetCidrPairDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KmsKey) DeepCopyInto(out *KmsKey) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KmsKey.
func (in *KmsKey) DeepCopy() *KmsKey {
	if in == nil {
		return nil
	}
	out := new(KmsKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KmsKeyConfig) DeepCopyInto(out *KmsKeyConfig) {
	*out = *in
	if in.KmsKeyId != nil {
		in, out := &in.KmsKeyId, &out.KmsKeyId
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KmsKeyConfig.
func (in *KmsKeyConfig) DeepCopy() *KmsKeyConfig {
	if in == nil {
		return nil
	}
	out := new(KmsKeyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeletConfiguration) DeepCopyInto(out *KubeletConfiguration) {
	*out = *in
	if in.ClusterDNS != nil {
		in, out := &in.ClusterDNS, &out.ClusterDNS
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExtraArgs != nil {
		in, out := &in.ExtraArgs, &out.ExtraArgs
		*out = new(string)
		**out = **in
	}
	if in.NodeLabels != nil {
		in, out := &in.NodeLabels, &out.NodeLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MaxPods != nil {
		in, out := &in.MaxPods, &out.MaxPods
		*out = new(int32)
		**out = **in
	}
	if in.PodsPerCore != nil {
		in, out := &in.PodsPerCore, &out.PodsPerCore
		*out = new(int32)
		**out = **in
	}
	if in.SystemReserved != nil {
		in, out := &in.SystemReserved, &out.SystemReserved
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.KubeReserved != nil {
		in, out := &in.KubeReserved, &out.KubeReserved
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.EvictionHard != nil {
		in, out := &in.EvictionHard, &out.EvictionHard
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.EvictionSoft != nil {
		in, out := &in.EvictionSoft, &out.EvictionSoft
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.EvictionSoftGracePeriod != nil {
		in, out := &in.EvictionSoftGracePeriod, &out.EvictionSoftGracePeriod
		*out = make(map[string]v1.Duration, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.EvictionMaxPodGracePeriod != nil {
		in, out := &in.EvictionMaxPodGracePeriod, &out.EvictionMaxPodGracePeriod
		*out = new(int32)
		**out = **in
	}
	if in.ImageGCHighThresholdPercent != nil {
		in, out := &in.ImageGCHighThresholdPercent, &out.ImageGCHighThresholdPercent
		*out = new(int32)
		**out = **in
	}
	if in.ImageGCLowThresholdPercent != nil {
		in, out := &in.ImageGCLowThresholdPercent, &out.ImageGCLowThresholdPercent
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeletConfiguration.
func (in *KubeletConfiguration) DeepCopy() *KubeletConfiguration {
	if in == nil {
		return nil
	}
	out := new(KubeletConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LaunchAttachIscsiVolumeConfig) DeepCopyInto(out *LaunchAttachIscsiVolumeConfig) {
	*out = *in
	in.AttachVolumeDetails.DeepCopyInto(&out.AttachVolumeDetails)
	if in.AgentAutoIscsiLoginEnabled != nil {
		in, out := &in.AgentAutoIscsiLoginEnabled, &out.AgentAutoIscsiLoginEnabled
		*out = new(bool)
		**out = **in
	}
	if in.EncryptionInTransitType != nil {
		in, out := &in.EncryptionInTransitType, &out.EncryptionInTransitType
		*out = new(IscsiEncryptInTransitType)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LaunchAttachIscsiVolumeConfig.
func (in *LaunchAttachIscsiVolumeConfig) DeepCopy() *LaunchAttachIscsiVolumeConfig {
	if in == nil {
		return nil
	}
	out := new(LaunchAttachIscsiVolumeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LaunchAttachParavirtualizedVolumeConfig) DeepCopyInto(out *LaunchAttachParavirtualizedVolumeConfig) {
	*out = *in
	in.AttachVolumeDetails.DeepCopyInto(&out.AttachVolumeDetails)
	if in.PvEncryptionInTransit != nil {
		in, out := &in.PvEncryptionInTransit, &out.PvEncryptionInTransit
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LaunchAttachParavirtualizedVolumeConfig.
func (in *LaunchAttachParavirtualizedVolumeConfig) DeepCopy() *LaunchAttachParavirtualizedVolumeConfig {
	if in == nil {
		return nil
	}
	out := new(LaunchAttachParavirtualizedVolumeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LaunchAttachVolumeConfig) DeepCopyInto(out *LaunchAttachVolumeConfig) {
	*out = *in
	if in.IscsiVolumeConfig != nil {
		in, out := &in.IscsiVolumeConfig, &out.IscsiVolumeConfig
		*out = new(LaunchAttachIscsiVolumeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ParavirtualizedVolumeConfig != nil {
		in, out := &in.ParavirtualizedVolumeConfig, &out.ParavirtualizedVolumeConfig
		*out = new(LaunchAttachParavirtualizedVolumeConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LaunchAttachVolumeConfig.
func (in *LaunchAttachVolumeConfig) DeepCopy() *LaunchAttachVolumeConfig {
	if in == nil {
		return nil
	}
	out := new(LaunchAttachVolumeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LaunchOptions) DeepCopyInto(out *LaunchOptions) {
	*out = *in
	if in.BootVolumeType != nil {
		in, out := &in.BootVolumeType, &out.BootVolumeType
		*out = new(VolumeType)
		**out = **in
	}
	if in.RemoteDataVolumeType != nil {
		in, out := &in.RemoteDataVolumeType, &out.RemoteDataVolumeType
		*out = new(VolumeType)
		**out = **in
	}
	if in.Firmware != nil {
		in, out := &in.Firmware, &out.Firmware
		*out = new(Firmware)
		**out = **in
	}
	if in.NetworkType != nil {
		in, out := &in.NetworkType, &out.NetworkType
		*out = new(NetworkType)
		**out = **in
	}
	if in.ConsistentVolumeNamingEnabled != nil {
		in, out := &in.ConsistentVolumeNamingEnabled, &out.ConsistentVolumeNamingEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LaunchOptions.
func (in *LaunchOptions) DeepCopy() *LaunchOptions {
	if in == nil {
		return nil
	}
	out := new(LaunchOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Network) DeepCopyInto(out *Network) {
	*out = *in
	if in.PrimaryVnic != nil {
		in, out := &in.PrimaryVnic, &out.PrimaryVnic
		*out = new(Vnic)
		(*in).DeepCopyInto(*out)
	}
	if in.SecondaryVnics != nil {
		in, out := &in.SecondaryVnics, &out.SecondaryVnics
		*out = make([]*Vnic, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Vnic)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Network.
func (in *Network) DeepCopy() *Network {
	if in == nil {
		return nil
	}
	out := new(Network)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkConfig) DeepCopyInto(out *NetworkConfig) {
	*out = *in
	if in.PrimaryVnicConfig != nil {
		in, out := &in.PrimaryVnicConfig, &out.PrimaryVnicConfig
		*out = new(SimpleVnicConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SecondaryVnicConfigs != nil {
		in, out := &in.SecondaryVnicConfigs, &out.SecondaryVnicConfigs
		*out = make([]*SecondaryVnicConfig, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(SecondaryVnicConfig)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkConfig.
func (in *NetworkConfig) DeepCopy() *NetworkConfig {
	if in == nil {
		return nil
	}
	out := new(NetworkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSecurityGroup) DeepCopyInto(out *NetworkSecurityGroup) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSecurityGroup.
func (in *NetworkSecurityGroup) DeepCopy() *NetworkSecurityGroup {
	if in == nil {
		return nil
	}
	out := new(NetworkSecurityGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSecurityGroupConfig) DeepCopyInto(out *NetworkSecurityGroupConfig) {
	*out = *in
	if in.NetworkSecurityGroupId != nil {
		in, out := &in.NetworkSecurityGroupId, &out.NetworkSecurityGroupId
		*out = new(string)
		**out = **in
	}
	if in.NetworkSecurityGroupFilter != nil {
		in, out := &in.NetworkSecurityGroupFilter, &out.NetworkSecurityGroupFilter
		*out = new(OciResourceSelectorTerm)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSecurityGroupConfig.
func (in *NetworkSecurityGroupConfig) DeepCopy() *NetworkSecurityGroupConfig {
	if in == nil {
		return nil
	}
	out := new(NetworkSecurityGroupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCINodeClass) DeepCopyInto(out *OCINodeClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCINodeClass.
func (in *OCINodeClass) DeepCopy() *OCINodeClass {
	if in == nil {
		return nil
	}
	out := new(OCINodeClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OCINodeClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCINodeClassList) DeepCopyInto(out *OCINodeClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OCINodeClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCINodeClassList.
func (in *OCINodeClassList) DeepCopy() *OCINodeClassList {
	if in == nil {
		return nil
	}
	out := new(OCINodeClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OCINodeClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCINodeClassSpec) DeepCopyInto(out *OCINodeClassSpec) {
	*out = *in
	if in.ShapeConfigs != nil {
		in, out := &in.ShapeConfigs, &out.ShapeConfigs
		*out = make([]*ShapeConfig, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ShapeConfig)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.NodeCompartmentId != nil {
		in, out := &in.NodeCompartmentId, &out.NodeCompartmentId
		*out = new(string)
		**out = **in
	}
	if in.VolumeConfig != nil {
		in, out := &in.VolumeConfig, &out.VolumeConfig
		*out = new(VolumeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.NetworkConfig != nil {
		in, out := &in.NetworkConfig, &out.NetworkConfig
		*out = new(NetworkConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CapacityReservationConfigs != nil {
		in, out := &in.CapacityReservationConfigs, &out.CapacityReservationConfigs
		*out = make([]*CapacityReservationConfig, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(CapacityReservationConfig)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.ClusterPlacementGroupConfigs != nil {
		in, out := &in.ClusterPlacementGroupConfigs, &out.ClusterPlacementGroupConfigs
		*out = make([]*ClusterPlacementGroupConfig, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ClusterPlacementGroupConfig)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.ComputeClusterConfig != nil {
		in, out := &in.ComputeClusterConfig, &out.ComputeClusterConfig
		*out = new(ComputeClusterConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]map[string]string, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	if in.KubeletConfig != nil {
		in, out := &in.KubeletConfig, &out.KubeletConfig
		*out = new(KubeletConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.PreBootstrapInitScript != nil {
		in, out := &in.PreBootstrapInitScript, &out.PreBootstrapInitScript
		*out = new(string)
		**out = **in
	}
	if in.PostBootstrapInitScript != nil {
		in, out := &in.PostBootstrapInitScript, &out.PostBootstrapInitScript
		*out = new(string)
		**out = **in
	}
	if in.SshAuthorizedKeys != nil {
		in, out := &in.SshAuthorizedKeys, &out.SshAuthorizedKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LaunchOptions != nil {
		in, out := &in.LaunchOptions, &out.LaunchOptions
		*out = new(LaunchOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.AgentList != nil {
		in, out := &in.AgentList, &out.AgentList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCINodeClassSpec.
func (in *OCINodeClassSpec) DeepCopy() *OCINodeClassSpec {
	if in == nil {
		return nil
	}
	out := new(OCINodeClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCINodeClassStatus) DeepCopyInto(out *OCINodeClassStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]status.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Volume != nil {
		in, out := &in.Volume, &out.Volume
		*out = new(Volume)
		(*in).DeepCopyInto(*out)
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(Network)
		(*in).DeepCopyInto(*out)
	}
	if in.CapacityReservations != nil {
		in, out := &in.CapacityReservations, &out.CapacityReservations
		*out = make([]CapacityReservation, len(*in))
		copy(*out, *in)
	}
	if in.ClusterPlacementGroups != nil {
		in, out := &in.ClusterPlacementGroups, &out.ClusterPlacementGroups
		*out = make([]ClusterPlacementGroup, len(*in))
		copy(*out, *in)
	}
	if in.ComputeCluster != nil {
		in, out := &in.ComputeCluster, &out.ComputeCluster
		*out = new(ComputeCluster)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCINodeClassStatus.
func (in *OCINodeClassStatus) DeepCopy() *OCINodeClassStatus {
	if in == nil {
		return nil
	}
	out := new(OCINodeClassStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OciResourceSelectorTerm) DeepCopyInto(out *OciResourceSelectorTerm) {
	*out = *in
	if in.CompartmentId != nil {
		in, out := &in.CompartmentId, &out.CompartmentId
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]map[string]string, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OciResourceSelectorTerm.
func (in *OciResourceSelectorTerm) DeepCopy() *OciResourceSelectorTerm {
	if in == nil {
		return nil
	}
	out := new(OciResourceSelectorTerm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecondaryVnicConfig) DeepCopyInto(out *SecondaryVnicConfig) {
	*out = *in
	in.SimpleVnicConfig.DeepCopyInto(&out.SimpleVnicConfig)
	if in.ApplicationResource != nil {
		in, out := &in.ApplicationResource, &out.ApplicationResource
		*out = new(string)
		**out = **in
	}
	if in.IpCount != nil {
		in, out := &in.IpCount, &out.IpCount
		*out = new(int)
		**out = **in
	}
	if in.NicIndex != nil {
		in, out := &in.NicIndex, &out.NicIndex
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecondaryVnicConfig.
func (in *SecondaryVnicConfig) DeepCopy() *SecondaryVnicConfig {
	if in == nil {
		return nil
	}
	out := new(SecondaryVnicConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShapeConfig) DeepCopyInto(out *ShapeConfig) {
	*out = *in
	if in.BaselineOcpuUtilization != nil {
		in, out := &in.BaselineOcpuUtilization, &out.BaselineOcpuUtilization
		*out = new(BaselineOcpuUtilization)
		**out = **in
	}
	if in.Ocpus != nil {
		in, out := &in.Ocpus, &out.Ocpus
		*out = new(float32)
		**out = **in
	}
	if in.MemoryInGbs != nil {
		in, out := &in.MemoryInGbs, &out.MemoryInGbs
		*out = new(float32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShapeConfig.
func (in *ShapeConfig) DeepCopy() *ShapeConfig {
	if in == nil {
		return nil
	}
	out := new(ShapeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimpleVnicConfig) DeepCopyInto(out *SimpleVnicConfig) {
	*out = *in
	if in.SubnetAndNsgConfig != nil {
		in, out := &in.SubnetAndNsgConfig, &out.SubnetAndNsgConfig
		*out = new(SubnetAndNsgConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AssignIpV6Ip != nil {
		in, out := &in.AssignIpV6Ip, &out.AssignIpV6Ip
		*out = new(bool)
		**out = **in
	}
	if in.AssignPublicIp != nil {
		in, out := &in.AssignPublicIp, &out.AssignPublicIp
		*out = new(bool)
		**out = **in
	}
	if in.VnicDisplayName != nil {
		in, out := &in.VnicDisplayName, &out.VnicDisplayName
		*out = new(string)
		**out = **in
	}
	if in.Ipv6AddressIpv6SubnetCidrPairDetails != nil {
		in, out := &in.Ipv6AddressIpv6SubnetCidrPairDetails, &out.Ipv6AddressIpv6SubnetCidrPairDetails
		*out = make([]*Ipv6AddressIpv6SubnetCidrPairDetails, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Ipv6AddressIpv6SubnetCidrPairDetails)
				**out = **in
			}
		}
	}
	if in.SkipSourceDestCheck != nil {
		in, out := &in.SkipSourceDestCheck, &out.SkipSourceDestCheck
		*out = new(bool)
		**out = **in
	}
	if in.SecurityAttributes != nil {
		in, out := &in.SecurityAttributes, &out.SecurityAttributes
		*out = make(map[string]map[string]string, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimpleVnicConfig.
func (in *SimpleVnicConfig) DeepCopy() *SimpleVnicConfig {
	if in == nil {
		return nil
	}
	out := new(SimpleVnicConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Subnet) DeepCopyInto(out *Subnet) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Subnet.
func (in *Subnet) DeepCopy() *Subnet {
	if in == nil {
		return nil
	}
	out := new(Subnet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubnetAndNsgConfig) DeepCopyInto(out *SubnetAndNsgConfig) {
	*out = *in
	if in.SubnetConfig != nil {
		in, out := &in.SubnetConfig, &out.SubnetConfig
		*out = new(SubnetConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.NetworkSecurityGroupConfigs != nil {
		in, out := &in.NetworkSecurityGroupConfigs, &out.NetworkSecurityGroupConfigs
		*out = make([]*NetworkSecurityGroupConfig, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NetworkSecurityGroupConfig)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubnetAndNsgConfig.
func (in *SubnetAndNsgConfig) DeepCopy() *SubnetAndNsgConfig {
	if in == nil {
		return nil
	}
	out := new(SubnetAndNsgConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubnetConfig) DeepCopyInto(out *SubnetConfig) {
	*out = *in
	if in.SubnetId != nil {
		in, out := &in.SubnetId, &out.SubnetId
		*out = new(string)
		**out = **in
	}
	if in.SubnetFilter != nil {
		in, out := &in.SubnetFilter, &out.SubnetFilter
		*out = new(OciResourceSelectorTerm)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubnetConfig.
func (in *SubnetConfig) DeepCopy() *SubnetConfig {
	if in == nil {
		return nil
	}
	out := new(SubnetConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Vnic) DeepCopyInto(out *Vnic) {
	*out = *in
	out.Subnet = in.Subnet
	if in.NetworkSecurityGroups != nil {
		in, out := &in.NetworkSecurityGroups, &out.NetworkSecurityGroups
		*out = make([]NetworkSecurityGroup, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Vnic.
func (in *Vnic) DeepCopy() *Vnic {
	if in == nil {
		return nil
	}
	out := new(Vnic)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VnicConfig) DeepCopyInto(out *VnicConfig) {
	*out = *in
	in.SimpleVnicConfig.DeepCopyInto(&out.SimpleVnicConfig)
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.AllocateIPV6 != nil {
		in, out := &in.AllocateIPV6, &out.AllocateIPV6
		*out = new(bool)
		**out = **in
	}
	if in.AssignPrivateDnsRecord != nil {
		in, out := &in.AssignPrivateDnsRecord, &out.AssignPrivateDnsRecord
		*out = new(bool)
		**out = **in
	}
	if in.SkipSourceDestCheck != nil {
		in, out := &in.SkipSourceDestCheck, &out.SkipSourceDestCheck
		*out = new(bool)
		**out = **in
	}
	if in.Ipv6AddressIpv6SubnetCidrPairDetails != nil {
		in, out := &in.Ipv6AddressIpv6SubnetCidrPairDetails, &out.Ipv6AddressIpv6SubnetCidrPairDetails
		*out = make([]Ipv6AddressIpv6SubnetCidrPairDetails, len(*in))
		copy(*out, *in)
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]map[string]string, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VnicConfig.
func (in *VnicConfig) DeepCopy() *VnicConfig {
	if in == nil {
		return nil
	}
	out := new(VnicConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Volume) DeepCopyInto(out *Volume) {
	*out = *in
	if in.ImageCandidates != nil {
		in, out := &in.ImageCandidates, &out.ImageCandidates
		*out = make([]*Image, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Image)
				**out = **in
			}
		}
	}
	if in.KmsKeys != nil {
		in, out := &in.KmsKeys, &out.KmsKeys
		*out = make([]*KmsKey, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(KmsKey)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Volume.
func (in *Volume) DeepCopy() *Volume {
	if in == nil {
		return nil
	}
	out := new(Volume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeAttribute) DeepCopyInto(out *VolumeAttribute) {
	*out = *in
	if in.KmsKeyConfig != nil {
		in, out := &in.KmsKeyConfig, &out.KmsKeyConfig
		*out = new(KmsKeyConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SizeInGBs != nil {
		in, out := &in.SizeInGBs, &out.SizeInGBs
		*out = new(int64)
		**out = **in
	}
	if in.VpusPerGB != nil {
		in, out := &in.VpusPerGB, &out.VpusPerGB
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeAttribute.
func (in *VolumeAttribute) DeepCopy() *VolumeAttribute {
	if in == nil {
		return nil
	}
	out := new(VolumeAttribute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeConfig) DeepCopyInto(out *VolumeConfig) {
	*out = *in
	if in.BootVolumeConfig != nil {
		in, out := &in.BootVolumeConfig, &out.BootVolumeConfig
		*out = new(BootVolumeConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeConfig.
func (in *VolumeConfig) DeepCopy() *VolumeConfig {
	if in == nil {
		return nil
	}
	out := new(VolumeConfig)
	in.DeepCopyInto(out)
	return out
}
