# Karpenter Provider OCI
#
# Copyright (c) 2026 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/

name: Unit Tests

on:
  pull_request: { }
  push: { }
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.25.0
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: build the binary
        run: |
          make build

      - name: Run Unit Tests
        run: |
          make test

      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go install github.com/mattn/goveralls@latest
          goveralls -coverprofile=cover.out -service=github